//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportClientesEntities : DbContext
    {
        public ReportClientesEntities()
            : base("name=ReportClientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_ReporteClientes_Result> SP_ReporteClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReporteClientes_Result>("SP_ReporteClientes");
        }
    }
}
