//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FacturaEntiti : DbContext
    {
        public FacturaEntiti()
            : base("name=FacturaEntiti")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_ReporteFactura_Result> SP_ReporteFactura(Nullable<int> idpedido)
        {
            var idpedidoParameter = idpedido.HasValue ?
                new ObjectParameter("idpedido", idpedido) :
                new ObjectParameter("idpedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReporteFactura_Result>("SP_ReporteFactura", idpedidoParameter);
        }
    }
}
